### ISSUE TITLE
[BUG] ImageResponseDto s3URL

### ISSUE THREAD

**Issue by AtomicLiquors** [SNS-PJT/Backend#17]
## 설명
- 클라이언트에서 Post 검색 기능 구현 중, 응답 데이터의 image url에서 이상 발견
- 응답 데이터 중, image url에서 s3 url에 해당하는 자리에 null값이 대입됨
- 백엔드 코드 확인 결과, ImageResponseDto.java의 @Builder 메서드에서 "value s3Url is always null" 경고 메시지 확인

## 요청사항
- post 조회 시 Image URL에 s3Url이 정상적으로 포함되는지 확인 후 조치 또는 피드백 바람.

## 기타
- [점검사항] 이슈 등록 전 .properties 및 .yml 최신화 확인, 최신화된 develop 브랜치 pull 확인하였음
- @Value 어노테이션은 Bean으로 등록된 객체만 사용 가능하다는 정보를 확인함. 출처는 아래 링크.
https://kimcoder.tistory.com/415
- [캡쳐 화면] 
클라이언트 측에서 확인된 응답 데이터
![issue2](https://github.com/SNS-PJT/Backend/assets/95601940/c323a615-0142-450e-9111-1ce46dd2f3e7)

관련 백엔드 코드 캡쳐본
![issue3](https://github.com/SNS-PJT/Backend/assets/95601940/7aab8ae0-2c94-4621-ae81-81b65bfd9881)

**Comment by Joslynn20** [comment]
Image Url 관련하여 Image 도메인이 해당 Url을 변수로 가지고 있는 것으로 변경함.
